### ISSUE TITLE
Generazione file log training + grafici 

### ISSUE THREAD

**Issue by Sergio-Ltr** [fexed/CM-ML-project#6]

**Comment by fexed** [comment]
Ho fatto una prima struttura, per ora scrivo nei log semplicemente i valori di loss e validation loss ottenuti durante il training. Se avete altri dati da aggiungere fatemi sapere e provvedo.
I dati sono salvati come pickle, che è un modo molto semplice di serializzare dati in Python. Tra i commenti ho aggiunto un esempio di deserializzazione, così da avere un'idea.
La pull request è la #12 , pronta al merge
